-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 17:16:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ATMManagementDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS ATMManagementDB;
CREATE DATABASE IF NOT EXISTS ATMManagementDB;
USE ATMManagementDB;
-- -----------------------------------------------------
-- Table `bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank` ;

CREATE TABLE IF NOT EXISTS `bank` (
  `bank_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(45) NOT NULL,
  `currency_id` INT UNSIGNED NOT NULL,
  `security_measures` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bank_id`),
  UNIQUE INDEX `bank_id_UNIQUE` (`bank_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_account` ;

CREATE TABLE IF NOT EXISTS `bank_account` (
  `bank_account_id` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `bank_id` INT(10) UNSIGNED NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `debit_card_id` INT(16) UNSIGNED NOT NULL,
  `credit_card_id` INT(16) UNSIGNED NULL,
  `loan_id` INT(10) UNSIGNED NULL,
  `investments_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`bank_account_id`),
  INDEX `FK_bankAccount_bank_idx` (`bank_id` ASC) VISIBLE,
  UNIQUE INDEX `bank_account_id_UNIQUE` (`bank_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_bankAccount_bank`
    FOREIGN KEY (`bank_id`)
    REFERENCES `bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_owner_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_owner_id` ;

CREATE TABLE IF NOT EXISTS `account_owner_id` (
  `account_owner_id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_name` VARCHAR(45) NOT NULL,
  `SSN` INT(9) UNSIGNED NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `created_date` DATE NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  `investment_id` INT UNSIGNED NULL,
  PRIMARY KEY (`account_owner_id`),
  INDEX `FK_accountOwner_bankAccount_idx` (`bank_account_id` ASC) VISIBLE,
  UNIQUE INDEX `account_owner_id_UNIQUE` (`account_owner_id` ASC) VISIBLE,
  CONSTRAINT `FK_accountOwner_bankAccount`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `bank_account` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checking_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checking_account` ;

CREATE TABLE IF NOT EXISTS `checking_account` (
  `checking_account_id` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  `routing_number` INT(9) UNSIGNED NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 1.00,
  `debit_card_id` INT(16) UNSIGNED NOT NULL,
  `withdrawls_id` INT UNSIGNED NOT NULL,
  `deposits_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`checking_account_id`),
  INDEX `FK_checkingAccount_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  UNIQUE INDEX `checking_account_id_UNIQUE` (`checking_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_checkingAccount_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `savings_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `savings_account` ;

CREATE TABLE IF NOT EXISTS `savings_account` (
  `savings_account_id` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `routing_number` INT(9) UNSIGNED NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 1.00,
  `withdrawal_id` INT UNSIGNED NOT NULL,
  `deposits_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`savings_account_id`),
  INDEX `FK_savingsAccount_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  UNIQUE INDEX `savings_account_id_UNIQUE` (`savings_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_savingsAccount_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crypto_wallet_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crypto_wallet_account` ;

CREATE TABLE IF NOT EXISTS `crypto_wallet_account` (
  `crypto_wallet_account_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  `routing_number` INT(9) UNSIGNED NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 1.00,
  `date_created` DATE NOT NULL,
  PRIMARY KEY (`crypto_wallet_account_id`),
  INDEX `FK_cryptoAccount_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  UNIQUE INDEX `crypto_wallet_account_id_UNIQUE` (`crypto_wallet_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_cryptoAccount_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card` ;

CREATE TABLE IF NOT EXISTS `card` (
  `card_id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`card_id`),
  UNIQUE INDEX `card_id_UNIQUE` (`card_id` ASC) VISIBLE,
  INDEX `FK_card_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  CONSTRAINT `FK_card_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `credit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `credit_card` ;

CREATE TABLE IF NOT EXISTS `credit_card` (
  `credit_card_id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `card_owner_name` VARCHAR(45) NOT NULL,
  `cvv_number` INT(3) UNSIGNED NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 0.00,
  `owed_balalance` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  `payment_due_date` DATE NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `overall_total_spent` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`credit_card_id`),
  INDEX `PK_creditCard__idx` (`account_owner_id` ASC) VISIBLE,
  UNIQUE INDEX `credit_card_id_UNIQUE` (`credit_card_id` ASC) VISIBLE,
  CONSTRAINT `PK_creditCard_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debit_card` ;

CREATE TABLE IF NOT EXISTS `debit_card` (
  `debit_card_id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `card_owner_name` VARCHAR(45) NOT NULL,
  `pin_number` INT(4) UNSIGNED NOT NULL,
  `cvv_number` INT(3) UNSIGNED NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 1.00,
  `checing_account_id` INT(12) UNSIGNED NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `total_amount_spent` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`debit_card_id`),
  INDEX `FK_debitCard_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  INDEX `FK_debitCard_checkingAccount_idx` (`checing_account_id` ASC) VISIBLE,
  UNIQUE INDEX `debit_card_id_UNIQUE` (`debit_card_id` ASC) VISIBLE,
  CONSTRAINT `FK_debitCard_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_debitCard_checkingAccount`
    FOREIGN KEY (`checing_account_id`)
    REFERENCES `checking_account` (`checking_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transaction_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transaction_records` ;

CREATE TABLE IF NOT EXISTS `transaction_records` (
  `transaction_records_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `record_type` VARCHAR(45) NOT NULL,
  `transaction_year` INT(4) UNSIGNED NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  `card_id` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`transaction_records_id`),
  INDEX `FK_transactionRec_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  INDEX `FK_transactionRec_bankAccount_idx` (`bank_account_id` ASC) VISIBLE,
  UNIQUE INDEX `transaction_records_id_UNIQUE` (`transaction_records_id` ASC) VISIBLE,
  CONSTRAINT `FK_transactionRec_bankAccount`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `bank_account` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_transactionRec_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transaction_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transaction_reports` ;

CREATE TABLE IF NOT EXISTS `transaction_reports` (
  `transaction_reports_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaction_reports_type` VARCHAR(45) NOT NULL,
  `month_year` INT(6) UNSIGNED NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  `card_id` INT(12) UNSIGNED NOT NULL,
  `record_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transaction_reports_id`),
  INDEX `FK_transactionRep_bankAccount_idx` (`bank_account_id` ASC) VISIBLE,
  INDEX `FK_transactionRep_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  UNIQUE INDEX `transaction_reports_id_UNIQUE` (`transaction_reports_id` ASC) VISIBLE,
  CONSTRAINT `FK_transactionRep_bankAccount`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `bank_account` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_transactionRep_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withdrawal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `withdrawal` ;

CREATE TABLE IF NOT EXISTS `withdrawal` (
  `withdrawal_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `withdrawal_type` VARCHAR(45) NOT NULL,
  `amount` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  `date_time` DATETIME NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `checking_account_id` INT(12) UNSIGNED NOT NULL,
  `savings_account` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`withdrawal_id`),
  INDEX `FK_withdrawals_checkingAccount_idx` (`checking_account_id` ASC) VISIBLE,
  INDEX `FK_withdrawals_savingsAccount_idx` (`savings_account` ASC) VISIBLE,
  UNIQUE INDEX `withdrawal_id_UNIQUE` (`withdrawal_id` ASC) VISIBLE,
  CONSTRAINT `FK_withdrawals_checkingAccount`
    FOREIGN KEY (`checking_account_id`)
    REFERENCES `checking_account` (`checking_account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_withdrawals_savingsAccount`
    FOREIGN KEY (`savings_account`)
    REFERENCES `savings_account` (`savings_account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deposits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deposits` ;

CREATE TABLE IF NOT EXISTS `deposits` (
  `deposits_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `deposit_type` VARCHAR(45) NOT NULL,
  `amount` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  `date_time` DATETIME NOT NULL,
  `account_owner_id` INT(12) UNSIGNED NOT NULL,
  `checking_account_id` INT(12) UNSIGNED NOT NULL,
  `savings_account_id` INT(12) UNSIGNED NOT NULL,
  `total_amount` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`deposits_id`),
  INDEX `FK_deposits_checkingAccount_idx` (`checking_account_id` ASC) VISIBLE,
  INDEX `FK_deposits_savingsAccount_idx` (`savings_account_id` ASC) VISIBLE,
  UNIQUE INDEX `deposits_id_UNIQUE` (`deposits_id` ASC) VISIBLE,
  CONSTRAINT `FK_deposits_checkingAccount`
    FOREIGN KEY (`checking_account_id`)
    REFERENCES `checking_account` (`checking_account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_deposits_savingsAccount`
    FOREIGN KEY (`savings_account_id`)
    REFERENCES `savings_account` (`savings_account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loan` ;

CREATE TABLE IF NOT EXISTS `loan` (
  `loan_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `loan_type` VARCHAR(45) NOT NULL,
  `loan_amount` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  `intrest_rate` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  `date_time` DATETIME NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `FK_loan_bankAccount_idx` (`bank_account_id` ASC) VISIBLE,
  UNIQUE INDEX `loan_id_UNIQUE` (`loan_id` ASC) VISIBLE,
  CONSTRAINT `FK_loan_bankAccount`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `bank_account` (`bank_account_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget_tracker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budget_tracker` ;

CREATE TABLE IF NOT EXISTS `budget_tracker` (
  `budget_tracker_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  `budget_amount` DOUBLE UNSIGNED NULL DEFAULT 0.00,
  PRIMARY KEY (`budget_tracker_id`),
  INDEX `FK_budgetTracker_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  CONSTRAINT `FK_budgetTracker_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency` ;

CREATE TABLE IF NOT EXISTS `currency` (
  `currency_id` INT(180) UNSIGNED NOT NULL,
  `currency_type` VARCHAR(45) NOT NULL,
  `currency_balance` DOUBLE UNSIGNED NOT NULL DEFAULT 0.00,
  `bank_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`currency_id`),
  INDEX `FK_currency_bankID_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `FK_currency_bankID`
    FOREIGN KEY (`bank_id`)
    REFERENCES `bank` (`bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security_measures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `security_measures` ;

CREATE TABLE IF NOT EXISTS `security_measures` (
  `security_measures_id` VARCHAR(45) NOT NULL,
  `bank_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`security_measures_id`),
  INDEX `FK_securityMeasures_bankID_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `FK_securityMeasures_bankID`
    FOREIGN KEY (`bank_id`)
    REFERENCES `bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customer_support`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer_support` ;

CREATE TABLE IF NOT EXISTS `customer_support` (
  `customer_support_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `support_type` VARCHAR(45) NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `date_time` DATETIME NOT NULL,
  PRIMARY KEY (`customer_support_id`),
  INDEX `FK_customerSupport_accountOwner_idx` (`account_owner_id` ASC) VISIBLE,
  UNIQUE INDEX `customer_support_id_UNIQUE` (`customer_support_id` ASC) VISIBLE,
  CONSTRAINT `FK_customerSupport_accountOwner`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `investments` ;

CREATE TABLE IF NOT EXISTS `investments` (
  `investments_id` INT NOT NULL AUTO_INCREMENT,
  `bank_account_id` INT(12) UNSIGNED NOT NULL,
  `account_owner_id` INT(8) UNSIGNED NOT NULL,
  `stock_id` VARCHAR(45) NOT NULL,
  `stock_value` DOUBLE NOT NULL DEFAULT 0.00,
  `amount_of_shares` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`investments_id`),
  INDEX `FK_investments_accountOwnerID_idx` (`account_owner_id` ASC) VISIBLE,
  UNIQUE INDEX `investments_id_UNIQUE` (`investments_id` ASC) VISIBLE,
  CONSTRAINT `FK_investments_accountOwnerID`
    FOREIGN KEY (`account_owner_id`)
    REFERENCES `account_owner_id` (`account_owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_pay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_pay` ;

CREATE TABLE IF NOT EXISTS `tap_pay` (
  `tap_pay_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE UNSIGNED NOT NULL,
  `date_time` DATETIME NOT NULL,
  `debit_card` INT(16) UNSIGNED NOT NULL,
  PRIMARY KEY (`tap_pay_id`),
  UNIQUE INDEX `tap_pay_id_UNIQUE` (`tap_pay_id` ASC) VISIBLE,
  INDEX `FK_tapPay_card_idx` (`debit_card` ASC) VISIBLE,
  CONSTRAINT `FK_tapPay_card`
    FOREIGN KEY (`debit_card`)
    REFERENCES `debit_card` (`debit_card_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
